### ISSUE TITLE
Navigating away from main page wrecks orb image path.

### ISSUE THREAD

**Issue by cedricwaxwing** [gitbot-eth/zodiac-mediawiki-skin#3]
Steps to reproduce:
- Click on "Discussion" from this page: http://137.184.52.171/mediawiki/index.php/ZODIAC.WIKI
- Notice that the orb image in the header is broken.
- Also, the monospaced font "Roboto Mono" is no longer available, and the tab font-family changes to default typography.

**Comment by asgeir-s** [comment]
I solved the broken orb image. However, I am not sure what is the problem with the font, the tab fonts look the same to me when clicking "Discussion":
![Screenshot 2022-05-20 at 12 57 46](https://user-images.githubusercontent.com/2156509/169514291-6aeda97d-5e23-4c49-be55-0affb6677be6.png)
and here:
![Screenshot 2022-05-20 at 13 00 24](https://user-images.githubusercontent.com/2156509/169514543-b6c31b8b-9e06-4ed9-829a-f52a552a1e24.png)
